const cropImageMapping: Record<string, string> = {
  고구마: 'sweetPotato',
  감자: 'potato',
  밀: 'wheat',
  쌀: 'rice',
  옥수수: 'corn',
  보리: 'barley',
  양배추: 'cabbage',
  토마토: 'tomato',
  브로콜리: 'broccoli',
  피망: 'bellPepper',
  호박: 'pumpkin',
  오이: 'cucumber',
  당근: 'carrot',
  시금치: 'spinach',
  마늘: 'garlic',
  사과: 'apple',
  포도: 'grape',
  딸기: 'strawberry',
  녹두: 'mungBean',
  수박: 'watermelon',
  샤인머스캣: 'shineMuscat',
  카카오: 'cacao',
};

export default cropImageMapping;
